### ISSUE TITLE
Különleges "lezáró" jegyek kezelése - Főoldali kártya

### ISSUE THREAD

**Issue by RedyAu** [filc/naplo#155]
```
NoSuchMethodError: The getter 'index' was called on null.
Receiver: null
Tried calling: index
```

```
#0      FeedBuilder.build.<anonymous closure> (package:filcnaplo/ui/pages/home/builder.dart:45)
#1      _GrowableList.forEach (dart:core-patch/growable_array.dart:403)
#2      FeedBuilder.build (package:filcnaplo/ui/pages/home/builder.dart:37)
#3      _HomePageState.initState (package:filcnaplo/ui/pages/home/page.dart:23)
#4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4704)
#5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4541)
#6      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3603)
#7      Element.updateChild (package:flutter/src/widgets/framework.dart:3358)
#8      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4592)
#9      Element.rebuild (package:flutter/src/widgets/framework.dart:4261)
#10     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4546)
```

**Comment by RedyAu** [comment]
Viszonylag hamar volna jó fixelni a hamarosan beírandó év végi jegyek miatt.
