### ISSUE TITLE
Bad state no element

### ISSUE THREAD

**Issue by 55nknown** [filc/naplo#73]
```
#0      ListIterable.reduce (dart:_internal/iterable.dart:181)
#1      _GradeGraphState.build.<anonymous closure> (package:filcnaplo_mobile_ui/pages/grades/graph.dart:90)
#2      WhereIterator.moveNext (dart:_internal/iterable.dart:439)
#3      new _GrowableList._ofOther (dart:core-patch/growable_array.dart:198)
#4      new _GrowableList.of (dart:core-patch/growable_array.dart:152)
#5      new List.of (dart:core-patch/array_patch.dart:51)
#6      SetMixin.toList (dart:collection/set.dart:118)
#7      _GradeGraphState.build (package:filcnaplo_mobile_ui/pages/grades/graph.dart:90)
```

**Comment by bru02** [comment]
happens when `subjectSpots` is empty

**Comment by 55nknown** [comment]
this too
